server:
    port: 8080

spring:
    artemis:
        mode: embedded

interlocking:
    signalling-system: SimpleSignallingSystem

    socket:
        server:
            ip: ''

    document:
        path: ''
