apiVersion: rail.yannick.sh/v1alpha1
kind: Block

metadata:
    name: block-2

spec:
    locked: false

    prohibits:
        block-3: block-4
        block-4: block-3

    switch:
        name: switch-SW1
        base: block-3
        alternate: block-4
