name: Maven Package

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Clone
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: adopt
                    java-version: 17

            -   name: Package
                run: mvn package
