name: Python Build

on: [ push ]

jobs:
    Linux:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            -   uses: actions/setup-python@v4
                with:
                    python-version: 3.11

            -   name: Install dependencies
                working-directory: ./digital-rail-concentrator
                run: python -m pip install --upgrade pip flake8 wheel

            -   name: Build
                working-directory: ./digital-rail-concentrator
                run: python setup.py bdist_wheel build

            -   name: Code linting
                working-directory: ./digital-rail-concentrator
                run: flake8 . --count --select=E9,F63,F7,F82 --show-source --exit-zero --max-complexity=10 --max-line-length=140  --statistics
